name: Pull Request Approve
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull Request 작성자 Slack ID 가져오기
        id: pr_author
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const workers = JSON.parse(fs.readFileSync('.github/workflows/reviewers.json'));
            const authorId = workers[context.payload.pull_request.user.login];
            return authorId;
          result-encoding: string

      - name: PR 작성자에게 Approve 알림 보내기
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ steps.pr_author.outputs.result }} # PR 작성자의 Slack ID
          payload: |
            {
              "text": "PR Approve 알림",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@${{ steps.pr_author.outputs.result }}>님의 PR이 Approve 되었습니다.\n • 제목: ${{ github.event.pull_request.title }}\n • 승인자: <@${{ github.event.review.user.login }}>\n • 링크: <${{ github.event.pull_request.html_url }}|머지하러 가기>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
