name: PR Workflow

on:
  pull_request:
    types: [opened, review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    # PR이 처음 열렸을 때만 라벨 추가
    if: github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3

      - name: Add D-day label
        uses: naver/simple-labeler@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "D-3"
          duplicate: "D-*"

  notify_reviewer:
    runs-on: ubuntu-latest
    # PR이 처음 열렸을 때는 add_label job이 필요하고, review_requested일 때만 실행
    needs: [add_label]
    if: |
      github.event.action == 'review_requested' ||
      (github.event.action == 'opened' && github.event.pull_request.requested_reviewers[0] != null)
    steps:
      - uses: actions/checkout@v3

      - name: Get PR Info with Labels
        id: pr_info
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const dDayLabel = pr.labels
              .find(label => label.name.startsWith('D-'))?.name || 'D-3';
            core.setOutput('dday', dDayLabel);

      - name: 리뷰어 목록 가져오기
        id: reviewers
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const workers = JSON.parse(fs.readFileSync('.github/workflows/reviewers.json'));
            // Slack ID만 반환하도록 수정 (@ 기호 제외)
            const mentions = context.payload.pull_request.requested_reviewers.map((user) => {
              const login = user.login;
              return workers[login] || null;
            }).filter(id => id !== null);
            return JSON.stringify(mentions);
          result-encoding: string

      - name: PR 리뷰어들에게 개별 DM 보내기
        uses: actions/github-script@v6
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          script: |
            const https = require('https');
            const reviewers = JSON.parse('${{ steps.reviewers.outputs.result }}');
            const dDayLabel = '${{ steps.pr_info.outputs.dday }}';

            for (const reviewer of reviewers) {
              const message = {
                channel: reviewer,
                text: "PR 리뷰 요청",
                blocks: [
                  {
                    type: "section",
                    text: {
                      type: "mrkdwn",
                      text: `<@${reviewer}>님 리뷰어로 할당되었습니다.\n • 제목: ${{ github.event.pull_request.title }}\n • 마감: ${dDayLabel}\n • 링크: <${{ github.event.pull_request.html_url }}|리뷰하러 가기>`
                    }
                  }
                ]
              };

              const options = {
                hostname: 'slack.com',
                path: '/api/chat.postMessage',
                method: 'POST',
                headers: {
                  'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`,
                  'Content-Type': 'application/json'
                }
              };

              const req = https.request(options, (res) => {
                let data = '';
                res.on('data', (chunk) => { data += chunk; });
                res.on('end', () => {
                  console.log('Slack response:', data);
                });
              });

              req.on('error', (error) => {
                console.error('Error:', error);
              });

              req.write(JSON.stringify(message));
              req.end();
            }
